"""Hash the actual Windows CPU wheels matching the installed environment.

Explicit setup only: first download the pinned wheels into runtime/wheelhouse.
Never derives wheel hashes from installed package RECORD files.
"""
import argparse
from email.parser import BytesParser
import hashlib
from importlib import metadata
import json
from pathlib import Path
import platform
import sys
import zipfile

from packaging.tags import sys_tags
from packaging.utils import canonicalize_name, parse_wheel_filename
from packaging.version import Version


def write_lock(root: Path, wheelhouse: Path) -> int:
    if sys.platform != 'win32' or platform.machine() != 'AMD64' or sys.version_info[:2] != (3, 12):
        raise ValueError('This lock targets CPython 3.12 on Windows AMD64')
    installed = {canonicalize_name(d.metadata['Name']): d for d in metadata.distributions()
                 if canonicalize_name(d.metadata['Name']) != 'vertebrate'}
    compatible = set(sys_tags())
    wheels = {}
    for path in sorted(wheelhouse.glob('*.whl')):
        name, version, _, tags = parse_wheel_filename(path.name)
        if name not in installed or version != Version(installed[name].version) or not tags & compatible:
            continue
        if name in wheels:
            raise ValueError(f'Ambiguous compatible wheels for {name}; use a dedicated wheelhouse')
        with zipfile.ZipFile(path) as archive:
            members = [n for n in archive.namelist()
                       if n.count('/') == 1 and n.endswith('.dist-info/METADATA')]
            if len(members) != 1:
                raise ValueError(f'{path.name}: expected one distribution METADATA')
            info = BytesParser().parsebytes(archive.read(members[0]))
            if canonicalize_name(info['Name']) != name or Version(info['Version']) != version:
                raise ValueError(f'{path.name}: filename and distribution metadata disagree')
        with path.open('rb') as stream:
            digest = hashlib.file_digest(stream, 'sha256').hexdigest()
        wheels[name] = {'name': installed[name].metadata['Name'], 'version': str(version),
                        'filename': path.name, 'sha256': digest, 'size_bytes': path.stat().st_size}
    missing = installed.keys() - wheels.keys()
    if missing:
        raise ValueError(f'Missing matching wheels: {sorted(missing)}; lock left unchanged')
    for name in ('torch', 'torchvision'):
        if not wheels[name]['version'].endswith('+cpu'):
            raise ValueError(f'{name} must use the CPU build')
    lines = ['# CPython 3.12 / Windows AMD64. Exact versions and SHA-256 of actual wheels.',
             '# Generated by tools/lock_wheels.py; install the project separately with --no-deps.',
             '--index-url https://pypi.org/simple',
             '--extra-index-url https://download.pytorch.org/whl/cpu',
             '--only-binary=:all:', '--require-hashes', '']
    records = [wheels[name] for name in sorted(wheels)]
    for row in records:
        lines.extend([f"# {row['filename']}",
                      f"{row['name']}=={row['version']} --hash=sha256:{row['sha256']}"])
    (root / 'requirements-win-cpu.lock').write_text('\n'.join(lines) + '\n', encoding='utf-8')
    (root / 'reports/wheel-manifest.json').write_text(json.dumps({
        'python': sys.version, 'platform': platform.platform(), 'wheels': records,
    }, indent=2) + '\n', encoding='utf-8')
    return len(records)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--wheelhouse', type=Path, default=Path('runtime/wheelhouse'))
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[1]
    count = write_lock(root, args.wheelhouse.resolve())
    print(f'Locked {count} installed packages to verified local wheel SHA-256 hashes.')
